/**
 * Demo IoT machine sensor data — simulated real-time machine readings
 * from connected manufacturing equipment on the production lines.
 */

const DEMO_MACHINES = [
  {
    id: 'mch-1',
    name: 'Grinder A-1',
    type: 'Industrial Grinder',
    line: 'Line 1',
    lineNumber: 1,
    status: 'running',
    outputRate: 482,
    targetOutput: 500,
    unit: 'lbs/hr',
    uptime: 98.4,
    lastMaintenance: '2026-06-10T08:00:00Z',
    nextMaintenance: '2026-06-20T08:00:00Z',
    sensors: {
      temperature: { value: 38, unit: '°F', min: 28, max: 45, threshold: 42 },
      vibration: { value: 2.4, unit: 'mm/s', min: 0, max: 10, threshold: 7.0 },
      powerDraw: { value: 18.2, unit: 'kW', min: 0, max: 25, threshold: 22 },
      motorRPM: { value: 1740, unit: 'RPM', min: 0, max: 1800, threshold: 1780 },
    },
    alerts: [],
  },
  {
    id: 'mch-2',
    name: 'Grinder A-2',
    type: 'Industrial Grinder',
    line: 'Line 1',
    lineNumber: 1,
    status: 'fault',
    outputRate: 0,
    targetOutput: 500,
    unit: 'lbs/hr',
    uptime: 72.1,
    lastMaintenance: '2026-06-08T08:00:00Z',
    nextMaintenance: '2026-06-18T08:00:00Z',
    sensors: {
      temperature: { value: 58, unit: '°F', min: 28, max: 45, threshold: 42 },
      vibration: { value: 9.8, unit: 'mm/s', min: 0, max: 10, threshold: 7.0 },
      powerDraw: { value: 24.1, unit: 'kW', min: 0, max: 25, threshold: 22 },
      motorRPM: { value: 0, unit: 'RPM', min: 0, max: 1800, threshold: 1780 },
    },
    alerts: [
      {
        id: 'alrt-2a',
        timestamp: '2026-06-15T17:22:05Z',
        severity: 'critical',
        type: 'motor_fault',
        message: 'Motor bearing failure detected — immediate maintenance required',
        acknowledged: false,
      },
      {
        id: 'alrt-2b',
        timestamp: '2026-06-15T17:20:12Z',
        severity: 'critical',
        type: 'over_temperature',
        message: 'Temperature exceeded safe threshold (58°F > 42°F limit)',
        acknowledged: false,
      },
      {
        id: 'alrt-2c',
        timestamp: '2026-06-15T17:19:45Z',
        severity: 'warning',
        type: 'abnormal_vibration',
        message: 'Vibration spike detected (9.8 mm/s exceeds 7.0 mm/s threshold)',
        acknowledged: true,
      },
    ],
  },
  {
    id: 'mch-3',
    name: 'Conveyor Belt C-1',
    type: 'Belt Conveyor',
    line: 'Line 1',
    lineNumber: 1,
    status: 'running',
    outputRate: 1200,
    targetOutput: 1250,
    unit: 'lbs/hr',
    uptime: 99.2,
    lastMaintenance: '2026-06-12T08:00:00Z',
    nextMaintenance: '2026-06-26T08:00:00Z',
    sensors: {
      temperature: { value: 34, unit: '°F', min: 28, max: 45, threshold: 42 },
      vibration: { value: 1.2, unit: 'mm/s', min: 0, max: 10, threshold: 7.0 },
      powerDraw: { value: 5.4, unit: 'kW', min: 0, max: 10, threshold: 8.5 },
      beltSpeed: { value: 3.2, unit: 'ft/s', min: 0, max: 5, threshold: 4.5 },
    },
    alerts: [],
  },
  {
    id: 'mch-4',
    name: 'Trim Saw TS-1',
    type: 'Band Saw',
    line: 'Line 2',
    lineNumber: 2,
    status: 'running',
    outputRate: 340,
    targetOutput: 400,
    unit: 'cuts/hr',
    uptime: 94.6,
    lastMaintenance: '2026-06-11T08:00:00Z',
    nextMaintenance: '2026-06-21T08:00:00Z',
    sensors: {
      temperature: { value: 36, unit: '°F', min: 28, max: 45, threshold: 42 },
      vibration: { value: 3.8, unit: 'mm/s', min: 0, max: 10, threshold: 7.0 },
      powerDraw: { value: 12.7, unit: 'kW', min: 0, max: 18, threshold: 16 },
      bladeRPM: { value: 2850, unit: 'RPM', min: 0, max: 3200, threshold: 3100 },
    },
    alerts: [
      {
        id: 'alrt-4a',
        timestamp: '2026-06-15T16:45:00Z',
        severity: 'info',
        type: 'output_deviation',
        message: 'Output rate 15% below target — possible material variation',
        acknowledged: true,
      },
    ],
  },
  {
    id: 'mch-5',
    name: 'Vacuum Sealer VS-1',
    type: 'Vacuum Packer',
    line: 'Line 2',
    lineNumber: 2,
    status: 'running',
    outputRate: 280,
    targetOutput: 300,
    unit: 'pkg/hr',
    uptime: 97.8,
    lastMaintenance: '2026-06-09T08:00:00Z',
    nextMaintenance: '2026-06-23T08:00:00Z',
    sensors: {
      temperature: { value: 32, unit: '°F', min: 28, max: 45, threshold: 42 },
      vibration: { value: 0.8, unit: 'mm/s', min: 0, max: 10, threshold: 7.0 },
      powerDraw: { value: 8.1, unit: 'kW', min: 0, max: 12, threshold: 10.5 },
      vacuumPressure: { value: -28.5, unit: 'inHg', min: -30, max: 0, threshold: -25 },
    },
    alerts: [],
  },
  {
    id: 'mch-6',
    name: 'Conveyor Belt C-3',
    type: 'Belt Conveyor',
    line: 'Line 3',
    lineNumber: 3,
    status: 'warning',
    outputRate: 950,
    targetOutput: 1250,
    unit: 'lbs/hr',
    uptime: 88.3,
    lastMaintenance: '2026-06-05T08:00:00Z',
    nextMaintenance: '2026-06-19T08:00:00Z',
    sensors: {
      temperature: { value: 41, unit: '°F', min: 28, max: 45, threshold: 42 },
      vibration: { value: 6.2, unit: 'mm/s', min: 0, max: 10, threshold: 7.0 },
      powerDraw: { value: 7.8, unit: 'kW', min: 0, max: 10, threshold: 8.5 },
      beltSpeed: { value: 2.1, unit: 'ft/s', min: 0, max: 5, threshold: 4.5 },
    },
    alerts: [
      {
        id: 'alrt-6a',
        timestamp: '2026-06-15T17:10:30Z',
        severity: 'warning',
        type: 'abnormal_vibration',
        message: 'Vibration trending high (6.2 mm/s, approaching 7.0 threshold)',
        acknowledged: false,
      },
      {
        id: 'alrt-6b',
        timestamp: '2026-06-15T17:05:15Z',
        severity: 'warning',
        type: 'output_deviation',
        message: 'Output rate 24% below target — belt speed reduced',
        acknowledged: false,
      },
    ],
  },
  {
    id: 'mch-7',
    name: 'Patty Former PF-1',
    type: 'Patty Machine',
    line: 'Line 5',
    lineNumber: 5,
    status: 'running',
    outputRate: 4800,
    targetOutput: 5000,
    unit: 'patties/hr',
    uptime: 96.9,
    lastMaintenance: '2026-06-13T08:00:00Z',
    nextMaintenance: '2026-06-27T08:00:00Z',
    sensors: {
      temperature: { value: 33, unit: '°F', min: 28, max: 45, threshold: 42 },
      vibration: { value: 2.1, unit: 'mm/s', min: 0, max: 10, threshold: 7.0 },
      powerDraw: { value: 14.5, unit: 'kW', min: 0, max: 20, threshold: 18 },
      formingPressure: { value: 45, unit: 'PSI', min: 0, max: 60, threshold: 55 },
    },
    alerts: [],
  },
  {
    id: 'mch-8',
    name: 'Metal Detector MD-2',
    type: 'Inline Detector',
    line: 'Line 2',
    lineNumber: 2,
    status: 'running',
    outputRate: 1200,
    targetOutput: 1200,
    unit: 'scans/hr',
    uptime: 99.9,
    lastMaintenance: '2026-06-14T08:00:00Z',
    nextMaintenance: '2026-06-28T08:00:00Z',
    sensors: {
      temperature: { value: 35, unit: '°F', min: 28, max: 45, threshold: 42 },
      vibration: { value: 0.3, unit: 'mm/s', min: 0, max: 10, threshold: 7.0 },
      powerDraw: { value: 2.1, unit: 'kW', min: 0, max: 5, threshold: 4 },
      sensitivity: { value: 99.2, unit: '%', min: 0, max: 100, threshold: 95 },
    },
    alerts: [],
  },
  {
    id: 'mch-9',
    name: 'Chiller Unit CH-1',
    type: 'Refrigeration',
    line: 'Line 1',
    lineNumber: 1,
    status: 'running',
    outputRate: 100,
    targetOutput: 100,
    unit: '%',
    uptime: 99.5,
    lastMaintenance: '2026-06-07T08:00:00Z',
    nextMaintenance: '2026-06-21T08:00:00Z',
    sensors: {
      temperature: { value: 30, unit: '°F', min: 28, max: 45, threshold: 42 },
      vibration: { value: 1.5, unit: 'mm/s', min: 0, max: 10, threshold: 7.0 },
      powerDraw: { value: 22.0, unit: 'kW', min: 0, max: 30, threshold: 27 },
      refrigerantPressure: { value: 185, unit: 'PSI', min: 150, max: 250, threshold: 230 },
    },
    alerts: [],
  },
  {
    id: 'mch-10',
    name: 'Box Labeler BL-1',
    type: 'Labeling Machine',
    line: 'Line 4',
    lineNumber: 4,
    status: 'idle',
    outputRate: 0,
    targetOutput: 600,
    unit: 'labels/hr',
    uptime: 91.2,
    lastMaintenance: '2026-06-06T08:00:00Z',
    nextMaintenance: '2026-06-20T08:00:00Z',
    sensors: {
      temperature: { value: 35, unit: '°F', min: 28, max: 45, threshold: 42 },
      vibration: { value: 0.1, unit: 'mm/s', min: 0, max: 10, threshold: 7.0 },
      powerDraw: { value: 0.5, unit: 'kW', min: 0, max: 3, threshold: 2.5 },
      labelStock: { value: 42, unit: '%', min: 0, max: 100, threshold: 15 },
    },
    alerts: [
      {
        id: 'alrt-10a',
        timestamp: '2026-06-15T15:00:00Z',
        severity: 'info',
        type: 'scheduled_idle',
        message: 'Machine idle — Line 4 scheduled downtime',
        acknowledged: true,
      },
    ],
  },
  {
    id: 'mch-11',
    name: 'Deboning Robot DR-1',
    type: 'Robotic Arm',
    line: 'Line 3',
    lineNumber: 3,
    status: 'maintenance',
    outputRate: 0,
    targetOutput: 200,
    unit: 'pieces/hr',
    uptime: 85.0,
    lastMaintenance: '2026-06-15T14:00:00Z',
    nextMaintenance: '2026-06-29T08:00:00Z',
    sensors: {
      temperature: { value: 35, unit: '°F', min: 28, max: 45, threshold: 42 },
      vibration: { value: 0.0, unit: 'mm/s', min: 0, max: 10, threshold: 7.0 },
      powerDraw: { value: 0.2, unit: 'kW', min: 0, max: 15, threshold: 13 },
      jointStress: { value: 0, unit: 'N·m', min: 0, max: 150, threshold: 130 },
    },
    alerts: [
      {
        id: 'alrt-11a',
        timestamp: '2026-06-15T14:00:00Z',
        severity: 'info',
        type: 'maintenance',
        message: 'Scheduled maintenance — joint calibration in progress',
        acknowledged: true,
      },
    ],
  },
  {
    id: 'mch-12',
    name: 'Weigh Scale WS-3',
    type: 'Inline Scale',
    line: 'Line 3',
    lineNumber: 3,
    status: 'running',
    outputRate: 1180,
    targetOutput: 1200,
    unit: 'weigh/hr',
    uptime: 99.7,
    lastMaintenance: '2026-06-13T08:00:00Z',
    nextMaintenance: '2026-06-27T08:00:00Z',
    sensors: {
      temperature: { value: 34, unit: '°F', min: 28, max: 45, threshold: 42 },
      vibration: { value: 0.5, unit: 'mm/s', min: 0, max: 10, threshold: 7.0 },
      powerDraw: { value: 1.2, unit: 'kW', min: 0, max: 3, threshold: 2.5 },
      accuracy: { value: 99.8, unit: '%', min: 0, max: 100, threshold: 99 },
    },
    alerts: [],
  },
];

export default DEMO_MACHINES;
