/**
 * Demo Safety Zone data — simulated AI camera-monitored safety zones
 * with breach detection, violation logging, and compliance tracking.
 */

const SAFETY_ZONES = [
  {
    id: 'sz-1',
    name: 'Restricted Zone A — Grinder Area',
    type: 'restricted',
    camera: 'SZ-CAM-01',
    image: '/safety-zones/sz-cam-01.png',
    location: 'Processing Hall — Section A',
    status: 'breach',
    severity: 'critical',
    zoneColor: '#DC2626',
    description: 'No unauthorized personnel. Active machinery hazard.',
    breachCount: 3,
    todayBreaches: 1,
    lastBreach: '2024-06-15T14:23:07Z',
  },
  {
    id: 'sz-2',
    name: 'Conveyor Belt Zone — Loading Dock',
    type: 'caution',
    camera: 'SZ-CAM-02',
    image: '/safety-zones/sz-cam-02.png',
    location: 'Loading Dock — Bay 3',
    status: 'breach',
    severity: 'warning',
    zoneColor: '#F59E0B',
    description: 'Active conveyor area. Authorized technicians only.',
    breachCount: 7,
    todayBreaches: 2,
    lastBreach: '2024-06-15T14:25:31Z',
  },
  {
    id: 'sz-3',
    name: 'Forklift Operating Area',
    type: 'restricted',
    camera: 'SZ-CAM-03',
    image: '/safety-zones/sz-cam-03.png',
    location: 'Warehouse — Aisle 4',
    status: 'breach',
    severity: 'warning',
    zoneColor: '#F97316',
    description: 'Forklift-only zone. Pedestrians must use marked walkways.',
    breachCount: 12,
    todayBreaches: 3,
    lastBreach: '2024-06-15T09:15:42Z',
  },
  {
    id: 'sz-4',
    name: 'High Voltage — Electrical Panel',
    type: 'restricted',
    camera: 'SZ-CAM-04',
    image: '/safety-zones/sz-cam-04.png',
    location: 'Cold Storage — Utility Corridor',
    status: 'breach',
    severity: 'critical',
    zoneColor: '#DC2626',
    description: 'High voltage area. Certified electricians only.',
    breachCount: 1,
    todayBreaches: 1,
    lastBreach: '2024-06-15T11:08:55Z',
  },
  {
    id: 'sz-5',
    name: 'Emergency Exit Path — Packaging',
    type: 'emergency',
    camera: 'SZ-CAM-05',
    image: '/safety-zones/sz-cam-05.png',
    location: 'Packaging Hall — Exit B',
    status: 'clear',
    severity: 'clear',
    zoneColor: '#10B981',
    description: 'Emergency evacuation route. Must remain unobstructed.',
    breachCount: 0,
    todayBreaches: 0,
    lastBreach: null,
  },
  {
    id: 'sz-6',
    name: 'Robotic Arm Area — Automation',
    type: 'restricted',
    camera: 'SZ-CAM-06',
    image: '/safety-zones/sz-cam-06.png',
    location: 'Processing Hall — Section C',
    status: 'breach',
    severity: 'critical',
    zoneColor: '#DC2626',
    description: 'Automated machinery zone. Lockout/tagout required for entry.',
    breachCount: 2,
    todayBreaches: 1,
    lastBreach: '2024-06-15T15:02:33Z',
  },
  {
    id: 'sz-7',
    name: 'Wet Floor / Cleaning Zone',
    type: 'caution',
    camera: 'SZ-CAM-07',
    image: '/safety-zones/sz-cam-07.png',
    location: 'Processing Hall — Section B',
    status: 'breach',
    severity: 'warning',
    zoneColor: '#F59E0B',
    description: 'Active cleaning area. Slip hazard — non-slip footwear required.',
    breachCount: 5,
    todayBreaches: 1,
    lastBreach: '2024-06-15T16:30:12Z',
  },
  {
    id: 'sz-8',
    name: 'Truck Reversing Zone — Dock 6',
    type: 'restricted',
    camera: 'SZ-CAM-08',
    image: '/safety-zones/sz-cam-08.png',
    location: 'Loading Dock — Bay 6',
    status: 'breach',
    severity: 'critical',
    zoneColor: '#F97316',
    description: 'Active truck reversing area. No pedestrians during operations.',
    breachCount: 4,
    todayBreaches: 1,
    lastBreach: '2024-06-15T08:45:28Z',
  },
  {
    id: 'sz-9',
    name: 'Grinder Machinery Zone',
    type: 'restricted',
    camera: 'SZ-CAM-09',
    image: '/safety-zones/sz-cam-09.png',
    location: 'Grinding Room — Main Floor',
    status: 'clear',
    severity: 'clear',
    zoneColor: '#DC2626',
    description: 'Industrial grinder exclusion zone. Active monitoring.',
    breachCount: 0,
    todayBreaches: 0,
    lastBreach: null,
  },
  {
    id: 'sz-10',
    name: 'Pedestrian Crossing — Intersection',
    type: 'caution',
    camera: 'SZ-CAM-10',
    image: '/safety-zones/sz-cam-10.png',
    location: 'Main Corridor — Junction C',
    status: 'breach',
    severity: 'warning',
    zoneColor: '#F59E0B',
    description: 'Pedestrian-only crossing zone. No vehicle traffic.',
    breachCount: 8,
    todayBreaches: 2,
    lastBreach: '2024-06-15T12:55:08Z',
  },
];

/**
 * Detailed violation/breach log entries across all zones.
 * These represent the AI detection events.
 */
const VIOLATION_LOG = [
  {
    id: 'vl-01',
    zoneId: 'sz-1',
    zoneName: 'Restricted Zone A — Grinder Area',
    camera: 'SZ-CAM-01',
    timestamp: '2024-06-15T14:23:07Z',
    severity: 'critical',
    type: 'unauthorized_entry',
    description: 'Worker entered restricted grinder zone without lockout clearance',
    person: 'Unidentified — Badge not scanned',
    duration: '47 sec',
    status: 'unresolved',
    image: '/safety-zones/sz-cam-01.png',
  },
  {
    id: 'vl-02',
    zoneId: 'sz-2',
    zoneName: 'Conveyor Belt Zone — Loading Dock',
    camera: 'SZ-CAM-02',
    timestamp: '2024-06-15T14:25:31Z',
    severity: 'warning',
    type: 'boundary_breach',
    description: 'Personnel crossed conveyor safety boundary during operation',
    person: 'Badge #1042 — M. Rodriguez',
    duration: '12 sec',
    status: 'acknowledged',
    image: '/safety-zones/sz-cam-02.png',
  },
  {
    id: 'vl-03',
    zoneId: 'sz-3',
    zoneName: 'Forklift Operating Area',
    camera: 'SZ-CAM-03',
    timestamp: '2024-06-15T09:15:42Z',
    severity: 'warning',
    type: 'pedestrian_in_vehicle_zone',
    description: 'Pedestrian entered active forklift operating zone',
    person: 'Badge #2087 — J. Thompson',
    duration: '23 sec',
    status: 'resolved',
    image: '/safety-zones/sz-cam-03.png',
  },
  {
    id: 'vl-04',
    zoneId: 'sz-4',
    zoneName: 'High Voltage — Electrical Panel',
    camera: 'SZ-CAM-04',
    timestamp: '2024-06-15T11:08:55Z',
    severity: 'critical',
    type: 'unauthorized_entry',
    description: 'Maintenance worker accessed high voltage panel without clearance',
    person: 'Badge #3021 — D. Williams',
    duration: '2 min 14 sec',
    status: 'unresolved',
    image: '/safety-zones/sz-cam-04.png',
  },
  {
    id: 'vl-05',
    zoneId: 'sz-6',
    zoneName: 'Robotic Arm Area — Automation',
    camera: 'SZ-CAM-06',
    timestamp: '2024-06-15T15:02:33Z',
    severity: 'critical',
    type: 'unauthorized_entry',
    description: 'Worker entered robotic arm zone without PPE or lockout procedure',
    person: 'Unidentified — No badge detected',
    duration: '1 min 38 sec',
    status: 'unresolved',
    image: '/safety-zones/sz-cam-06.png',
  },
  {
    id: 'vl-06',
    zoneId: 'sz-7',
    zoneName: 'Wet Floor / Cleaning Zone',
    camera: 'SZ-CAM-07',
    timestamp: '2024-06-15T16:30:12Z',
    severity: 'warning',
    type: 'slip_hazard_entry',
    description: 'Worker entered wet cleaning zone without non-slip footwear',
    person: 'Badge #1588 — K. Nguyen',
    duration: '8 sec',
    status: 'resolved',
    image: '/safety-zones/sz-cam-07.png',
  },
  {
    id: 'vl-07',
    zoneId: 'sz-8',
    zoneName: 'Truck Reversing Zone — Dock 6',
    camera: 'SZ-CAM-08',
    timestamp: '2024-06-15T08:45:28Z',
    severity: 'critical',
    type: 'pedestrian_in_vehicle_zone',
    description: 'Worker walked behind reversing truck in dock zone',
    person: 'Badge #4102 — R. Patel',
    duration: '15 sec',
    status: 'acknowledged',
    image: '/safety-zones/sz-cam-08.png',
  },
  {
    id: 'vl-08',
    zoneId: 'sz-10',
    zoneName: 'Pedestrian Crossing — Intersection',
    camera: 'SZ-CAM-10',
    timestamp: '2024-06-15T12:55:08Z',
    severity: 'warning',
    type: 'vehicle_in_pedestrian_zone',
    description: 'Forklift entered pedestrian-only crossing zone',
    person: 'Forklift Operator — Badge #2044',
    duration: '31 sec',
    status: 'unresolved',
    image: '/safety-zones/sz-cam-10.png',
  },
  {
    id: 'vl-09',
    zoneId: 'sz-3',
    zoneName: 'Forklift Operating Area',
    camera: 'SZ-CAM-03',
    timestamp: '2024-06-15T07:42:15Z',
    severity: 'warning',
    type: 'pedestrian_in_vehicle_zone',
    description: 'Morning shift worker cut through forklift zone as shortcut',
    person: 'Badge #1923 — S. Martinez',
    duration: '19 sec',
    status: 'resolved',
    image: '/safety-zones/sz-cam-03.png',
  },
  {
    id: 'vl-10',
    zoneId: 'sz-2',
    zoneName: 'Conveyor Belt Zone — Loading Dock',
    camera: 'SZ-CAM-02',
    timestamp: '2024-06-15T11:14:03Z',
    severity: 'warning',
    type: 'boundary_breach',
    description: 'Worker reached across conveyor safety boundary to retrieve item',
    person: 'Badge #1042 — M. Rodriguez',
    duration: '6 sec',
    status: 'resolved',
    image: '/safety-zones/sz-cam-02.png',
  },
  {
    id: 'vl-11',
    zoneId: 'sz-10',
    zoneName: 'Pedestrian Crossing — Intersection',
    camera: 'SZ-CAM-10',
    timestamp: '2024-06-15T10:30:22Z',
    severity: 'warning',
    type: 'vehicle_in_pedestrian_zone',
    description: 'Pallet jack driven through pedestrian crossing during shift change',
    person: 'Badge #3088 — T. Garcia',
    duration: '44 sec',
    status: 'acknowledged',
    image: '/safety-zones/sz-cam-10.png',
  },
  {
    id: 'vl-12',
    zoneId: 'sz-1',
    zoneName: 'Restricted Zone A — Grinder Area',
    camera: 'SZ-CAM-01',
    timestamp: '2024-06-14T16:05:41Z',
    severity: 'critical',
    type: 'unauthorized_entry',
    description: 'Two workers entered grinder zone during active operation',
    person: 'Multiple — Badge #2011, #2045',
    duration: '1 min 02 sec',
    status: 'resolved',
    image: '/safety-zones/sz-cam-01.png',
  },
];

export { SAFETY_ZONES, VIOLATION_LOG };
