/**
 * Demo production-line camera data — simulated top-down AI camera feeds
 * with foreign object detection capabilities.
 * Each entry represents a camera mounted above a production line.
 */

const DEMO_PRODUCTION_CAMERAS = [
  {
    id: 'plc-1',
    name: 'Line 1 — Intake Belt',
    line: 'Line 1',
    lineNumber: 1,
    location: 'Ground Beef Processing — Intake Section',
    cameraType: 'AI Vision — Top-Down',
    status: 'online',
    aiStatus: 'alert',
    aiConfidence: 97.2,
    detections: 2,
    image: '/camera-feeds/cam-03.png',
    lastDetection: '2026-06-15T17:28:14Z',
    events: [
      {
        id: 'evt-1a',
        timestamp: '2026-06-15T17:28:14Z',
        type: 'foreign_object',
        severity: 'critical',
        object: 'Metal Fragment',
        confidence: 97.2,
        action: 'Line paused — awaiting inspection',
        resolved: false,
      },
      {
        id: 'evt-1b',
        timestamp: '2026-06-15T17:25:03Z',
        type: 'foreign_object',
        severity: 'warning',
        object: 'Plastic Shard',
        confidence: 89.1,
        action: 'Flagged for review',
        resolved: false,
      },
      {
        id: 'evt-1c',
        timestamp: '2026-06-15T16:45:22Z',
        type: 'foreign_object',
        severity: 'warning',
        object: 'Rubber Piece',
        confidence: 82.3,
        action: 'Removed by operator',
        resolved: true,
      },
    ],
  },
  {
    id: 'plc-2',
    name: 'Line 1 — Grinder Output',
    line: 'Line 1',
    lineNumber: 1,
    location: 'Ground Beef Processing — Grinder Station',
    cameraType: 'AI Vision — Top-Down',
    status: 'online',
    aiStatus: 'clear',
    aiConfidence: 99.8,
    detections: 0,
    image: '/camera-feeds/cam-07.png',
    lastDetection: null,
    events: [],
  },
  {
    id: 'plc-3',
    name: 'Line 2 — Trim Sort',
    line: 'Line 2',
    lineNumber: 2,
    location: 'Trim Processing — Sorting Conveyor',
    cameraType: 'AI Vision — Top-Down',
    status: 'online',
    aiStatus: 'clear',
    aiConfidence: 99.4,
    detections: 0,
    image: '/camera-feeds/cam-08.png',
    lastDetection: '2026-06-15T14:12:08Z',
    events: [
      {
        id: 'evt-3a',
        timestamp: '2026-06-15T14:12:08Z',
        type: 'foreign_object',
        severity: 'info',
        object: 'Cardboard Fragment',
        confidence: 76.5,
        action: 'Auto-cleared — below threshold',
        resolved: true,
      },
    ],
  },
  {
    id: 'plc-4',
    name: 'Line 2 — Packaging Feed',
    line: 'Line 2',
    lineNumber: 2,
    location: 'Trim Processing — Pre-Package Belt',
    cameraType: 'AI Vision — Top-Down',
    status: 'online',
    aiStatus: 'warning',
    aiConfidence: 91.3,
    detections: 1,
    image: '/camera-feeds/cam-01.png',
    lastDetection: '2026-06-15T17:15:42Z',
    events: [
      {
        id: 'evt-4a',
        timestamp: '2026-06-15T17:15:42Z',
        type: 'foreign_object',
        severity: 'warning',
        object: 'Bone Fragment',
        confidence: 91.3,
        action: 'Operator notified',
        resolved: false,
      },
      {
        id: 'evt-4b',
        timestamp: '2026-06-15T15:30:11Z',
        type: 'foreign_object',
        severity: 'info',
        object: 'Fat Clump (false positive)',
        confidence: 62.1,
        action: 'Auto-dismissed',
        resolved: true,
      },
    ],
  },
  {
    id: 'plc-5',
    name: 'Line 3 — Chuck Conveyor',
    line: 'Line 3',
    lineNumber: 3,
    location: 'Chuck Processing — Main Belt',
    cameraType: 'AI Vision — Top-Down',
    status: 'online',
    aiStatus: 'clear',
    aiConfidence: 99.9,
    detections: 0,
    image: '/camera-feeds/cam-05.png',
    lastDetection: '2026-06-14T09:22:00Z',
    events: [],
  },
  {
    id: 'plc-6',
    name: 'Line 3 — Vacuum Pack',
    line: 'Line 3',
    lineNumber: 3,
    location: 'Chuck Processing — Vacuum Seal Station',
    cameraType: 'AI Vision — Top-Down',
    status: 'offline',
    aiStatus: 'offline',
    aiConfidence: 0,
    detections: 0,
    image: null,
    lastDetection: null,
    events: [],
  },
  {
    id: 'plc-7',
    name: 'Line 4 — Rib Eye Sort',
    line: 'Line 4',
    lineNumber: 4,
    location: 'Rib Eye Processing — Sorting Area',
    cameraType: 'AI Vision — Top-Down',
    status: 'online',
    aiStatus: 'clear',
    aiConfidence: 98.7,
    detections: 0,
    image: '/camera-feeds/cam-11.png',
    lastDetection: '2026-06-15T11:05:33Z',
    events: [
      {
        id: 'evt-7a',
        timestamp: '2026-06-15T11:05:33Z',
        type: 'foreign_object',
        severity: 'warning',
        object: 'Glove Fragment',
        confidence: 88.4,
        action: 'Removed by operator',
        resolved: true,
      },
    ],
  },
  {
    id: 'plc-8',
    name: 'Line 4 — Final Inspection',
    line: 'Line 4',
    lineNumber: 4,
    location: 'Rib Eye Processing — QC Belt',
    cameraType: 'AI Vision — Top-Down',
    status: 'online',
    aiStatus: 'critical',
    aiConfidence: 98.9,
    detections: 3,
    image: '/camera-feeds/cam-12.png',
    lastDetection: '2026-06-15T17:31:02Z',
    events: [
      {
        id: 'evt-8a',
        timestamp: '2026-06-15T17:31:02Z',
        type: 'foreign_object',
        severity: 'critical',
        object: 'Wire Fragment',
        confidence: 98.9,
        action: 'LINE STOPPED — Emergency halt',
        resolved: false,
      },
      {
        id: 'evt-8b',
        timestamp: '2026-06-15T17:30:45Z',
        type: 'foreign_object',
        severity: 'critical',
        object: 'Metal Shaving',
        confidence: 96.1,
        action: 'LINE STOPPED — Emergency halt',
        resolved: false,
      },
      {
        id: 'evt-8c',
        timestamp: '2026-06-15T17:29:58Z',
        type: 'foreign_object',
        severity: 'warning',
        object: 'Unknown Debris',
        confidence: 84.7,
        action: 'Flagged for review',
        resolved: false,
      },
    ],
  },
  {
    id: 'plc-9',
    name: 'Line 5 — Patty Former',
    line: 'Line 5',
    lineNumber: 5,
    location: 'Patty Line — Former Output',
    cameraType: 'AI Vision — Top-Down',
    status: 'online',
    aiStatus: 'clear',
    aiConfidence: 99.6,
    detections: 0,
    image: '/camera-feeds/cam-14.png',
    lastDetection: null,
    events: [],
  },
];

export default DEMO_PRODUCTION_CAMERAS;
