/**
 * Demo camera feed data — placeholder images for the camera monitoring UI.
 * Each entry represents a simulated camera with AI-detection overlay screenshots.
 * These are used when no real cameras are configured in the system.
 */

const DEMO_CAMERA_FEEDS = [
  {
    id: 'demo-1',
    name: 'Warehouse Floor A',
    location_description: 'Main Warehouse — Aisle 3-4',
    camera_type: 'fixed',
    zone: 'Floor',
    status: 'online',
    image: '/camera-feeds/cam-01.png',
  },
  {
    id: 'demo-2',
    name: 'Hallway B Corridor',
    location_description: 'Processing Wing — Corridor B',
    camera_type: 'fixed',
    zone: 'Floor',
    status: 'online',
    image: '/camera-feeds/cam-02.png',
  },
  {
    id: 'demo-3',
    name: 'Production Line 1',
    location_description: 'Main Floor — Line 1',
    camera_type: 'fixed',
    zone: 'Line',
    status: 'online',
    image: '/camera-feeds/cam-03.png',
  },
  {
    id: 'demo-4',
    name: 'Loading Dock East',
    location_description: 'East Dock — Bays 1-3',
    camera_type: 'ptz',
    zone: 'Entrance',
    status: 'online',
    image: '/camera-feeds/cam-04.png',
  },
  {
    id: 'demo-5',
    name: 'Cold Storage Room',
    location_description: 'Cold Storage — Section A',
    camera_type: 'fixed',
    zone: 'Hazard Zone',
    status: 'online',
    image: '/camera-feeds/cam-05.png',
  },
  {
    id: 'demo-6',
    name: 'Main Entrance Gate',
    location_description: 'Facility Entrance — Gate 1',
    camera_type: 'ptz',
    zone: 'Entrance',
    status: 'online',
    image: '/camera-feeds/cam-06.png',
  },
  {
    id: 'demo-7',
    name: 'Packaging Area',
    location_description: 'Packaging Wing — Stations 1-8',
    camera_type: 'fixed',
    zone: 'Line',
    status: 'online',
    image: '/camera-feeds/cam-07.png',
  },
  {
    id: 'demo-8',
    name: 'Conveyor Output',
    location_description: 'Automation Bay — Output Belt',
    camera_type: 'fixed',
    zone: 'Line',
    status: 'online',
    image: '/camera-feeds/cam-08.png',
  },
  {
    id: 'demo-9',
    name: 'Parking Lot',
    location_description: 'Exterior — Employee Parking',
    camera_type: 'ptz',
    zone: 'Entrance',
    status: 'online',
    image: '/camera-feeds/cam-09.png',
  },
  {
    id: 'demo-10',
    name: 'Hazard Zone North',
    location_description: 'Heavy Machinery — Zone N',
    camera_type: 'fixed',
    zone: 'Hazard Zone',
    status: 'online',
    image: '/camera-feeds/cam-10.png',
  },
  {
    id: 'demo-11',
    name: 'Factory Floor Overview',
    location_description: 'Main Floor — Ceiling Mount',
    camera_type: 'ptz',
    zone: 'Floor',
    status: 'online',
    image: '/camera-feeds/cam-11.png',
  },
  {
    id: 'demo-12',
    name: 'Maintenance Bay',
    location_description: 'Maintenance — Workshop',
    camera_type: 'fixed',
    zone: 'Floor',
    status: 'online',
    image: '/camera-feeds/cam-12.png',
  },
  {
    id: 'demo-13',
    name: 'Receiving Dock West',
    location_description: 'West Dock — Receiving',
    camera_type: 'fixed',
    zone: 'Entrance',
    status: 'online',
    image: '/camera-feeds/cam-13.png',
  },
  {
    id: 'demo-14',
    name: 'Quality Control Lab',
    location_description: 'QC Lab — Room 104',
    camera_type: 'fixed',
    zone: 'Floor',
    status: 'online',
    image: '/camera-feeds/cam-14.png',
  },
  {
    id: 'demo-15',
    name: 'Break Room',
    location_description: 'Employee Break Room — B Wing',
    camera_type: 'fixed',
    zone: 'Floor',
    status: 'online',
    image: '/camera-feeds/cam-15.png',
  },
  {
    id: 'demo-16',
    name: 'Exterior Building',
    location_description: 'Facility Exterior — Gate Cam',
    camera_type: 'ptz',
    zone: 'Entrance',
    status: 'online',
    image: '/camera-feeds/cam-16.png',
  },
];

export default DEMO_CAMERA_FEEDS;
